### ISSUE TITLE
usage example?

### ISSUE THREAD

**Issue by ahundt** [fferri/v_repStubsGen#2]
Would you mind adding a brief usage example for this, like perhaps a terminal session or screen recording that generates and builds a plugin with a lua function? 

I know of https://github.com/fferri/v_repExtPluginSkeletonNG, but am I correct that it is the final result, not the process to get there?

**Comment by fferri** [comment]
How to use this tool is described in https://github.com/fferri/v_repStubsGen/blob/master/README.md, i.e. you can run the tool with a `callbacks.xml` input and generate C++ code (stubs.cpp and stubs.h).

It does **not** generate a complete plugin, but only the wrappers for the Lua callbacks defined in `callbacks.xml`.

https://github.com/fferri/v_repExtPluginSkeletonNG is a usage example which shows how to integrate the above step into a CMake based plugin. It is a complete V-REP plugin using also this code generator.

It seems that you expected this tool to generate a complete plugin skeleton, which is not what it does, so I'm closing this issue. Reopen with new feedback in case I misunderstood you.

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repStubsGen#2
